name: Detect Changed Files in PR on Self-Hosted Runner

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  get_changed_files:
    runs-on: self-hosted  # This will run on your self-hosted runner
    
    steps:
    # Step 1: Checkout the repository code
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Get the list of changed files in the pull request
    - name: Get changed files
      run: |
        # Fetch the changes from the pull request branch
        git fetch origin pull/${{ github.event.pull_request.number }}/head:pr-branch
        # List the files that have changed
        git diff --name-only origin/main...pr-branch > changed_files.txt
        cat changed_files.txt

    # Step 3: Process the changed files (if needed)
    - name: Process changed files
      run: |
        while read file; do
          echo "File changed: $file"
          # You can add specific logic here for each changed file
        done < changed_files.txt
